const productos = [
    {
      id: 1,
      name: 'La Mr. Pit',
      description: 'Solo para expertos',
      price: '350',
      category: 'pizzas',
      image: '/assets/imagenes/lamrpit.png',
    },
    {
      id: 2,
      name: '¡Q Jamone',
      description: 'Con jamón crudo',
      price: '350',
      category: 'pizzas',
      image: '/assets/imagenes/qjamone.png',
    },
    {
      id: 3,
      name: 'La Charly García',
      description: '¡BASTA!',
      price: '380',
      category: 'pizzas',
      image: '/assets/imagenes/lacharlygarcia.png',
    },
    {
      id: 4,
      name: 'La Maradona',
      description: '¡Eterna!',
      price: '450',
      category: 'pizzas',
      image: '/assets/imagenes/lamaradona.png',
    },
    {
      id: 5,
      name: 'Picantovich',
      description: 'Pica dos veces',
      price: '750',
      category: 'pizzas',
      image: '/assets/imagenes/picantovich.png',
    },
    {
      id: 6,
      name: 'La Hasbulla',
      description: 'En honor al 1',
      price: '990',
      category: 'pizzas',
      image: '/assets/imagenes/lahasbulla.png',
    },
    {
      id: 7,
      name: 'Leo Messi',
      description: '¡De pie señores!',
      price: '10',
      category: 'pizzas',
      image: '/assets/imagenes/leomessi.png',
    },
    {
      id: 8,
      name: 'Nick Gi',
      description: 'La que desaparece',
      price: 'Gratis',
      category: 'pizzas',
      image: '/assets/imagenes/nickgi.png',
    },
    {
      id: 9,
      name: 'La Argenta',
      description: 'Una bomba',
      price: '750',
      category: 'hamburguesas',
      image: '/assets/imagenes/hamburguesa.jpg',
    },
    {
      id: 10,
      name: 'La L10nel',
      description: 'Una con 10 patys',
      price: '1550',
      category: 'hamburguesas',
      image: '/assets/imagenes/hamburguesa.jpg',
    },
    {
      id: 11,
      name: 'La triple T',
      description: 'con mucho tomate',
      price: '550',
      category: 'hamburguesas',
      image: '/assets/imagenes/hamburguesa.jpg',
    },
    {
      id: 12,
      name: 'La LGante',
      description: 'Hecha en 4:20 minutos',
      price: '350',
      category: 'hamburguesas',
      image: '/assets/imagenes/hamburguesa.jpg',
    },
    {
      id: 13,
      name: 'Las clásicas',
      description: 'Básicas',
      price: '450',
      category: 'papas',
      image: '/assets/imagenes/papasfritas.jpg',
    },
    {
      id: 14,
      name: 'La triple B',
      description: 'Bacon, Barbacoa y Barata',
      price: '150',
      category: 'papas',
      image: '/assets/imagenes/papasfritas.jpg',
    },
    {
      id: 15,
      name: 'Con Chencho',
      description: 'Con mucho cheddar',
      price: '600',
      category: 'papas',
      image: '/assets/imagenes/papasfritas.jpg',
    },
    {
      id: 16,
      name: 'Veganas',
      description: 'La cosa sana',
      price: '710',
      category: 'papas',
      image: '/assets/imagenes/papasfritas.jpg',
    },
    {
      id: 17,
      name: 'Picante',
      description: 'Picantovich',
      price: '710',
      category: 'wraps',
      image: '/assets/imagenes/wraps.jpg',
    },
    {
      id: 18,
      name: 'Frutal',
      description: 'Le mandamos ananá porque pintó',
      price: '530',
      category: 'wraps',
      image: '/assets/imagenes/wraps.jpg',
    },
    {
      id: 19,
      name: 'Livianito',
      description: 'No hace falta el boldo después',
      price: '670',
      category: 'wraps',
      image: '/assets/imagenes/wraps.jpg',
    },
    {
      id: 20,
      name: 'Armando ando',
      description: 'Te dejamos que elijas los ingredientes',
      price: '710',
      category: 'wraps',
      image: '/assets/imagenes/wraps.jpg',
    },
    {
      id: 21,
      name: 'Violeta',
      description: 'Con arandanos, avena y leche de almendras',
      price: '400',
      category: 'batidos',
      image: '/assets/imagenes/batidos.jpg',
    },
    {
      id: 22,
      name: 'Rosa',
      description: 'Con frutilla',
      price: '600',
      category: 'batidos',
      image: './assets/imagenes/batidos.jpg',
    },
    {
      id: 23,
      name: 'Verde',
      description: 'Con kiwi y leche de mani',
      price: '550',
      category: 'batidos',
      image: '/assets/imagenes/batidos.jpg',
    },
    {
      id: 24,
      name: 'Re verde',
      description: 'Kiwi, apio y menta',
      price: '450',
      category: 'batidos',
      image: '/assets/imagenes/batidos.jpg',
    },
  ];
  // console.log(productos)

  const separarProductos = (tamaño) => {
    let dividirProductos = []
    for(let i = 0; i < productos.length; i += tamaño){
      dividirProductos.push(productos.slice(i, i + tamaño))
    }
    return dividirProductos
  }
  
  const controladorDeProductos = {
    dividirProductos: separarProductos(8),
    siguienteProductosIndex: 1,
    productosLimite: separarProductos(8).length,
  }
